from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# --- Fixed-Income Curve Debate States ---


class DirectionDebateState(TypedDict):
    """State for the yield-direction debate (higher vs lower yields)."""
    higher_yields_history: Annotated[str, "Arguments for higher yields"]
    lower_yields_history: Annotated[str, "Arguments for lower yields"]
    history: Annotated[str, "Full debate conversation history"]
    current_response: Annotated[str, "Latest response in the debate"]
    judge_decision: Annotated[str, "Direction debate judge's decision"]
    count: Annotated[int, "Number of debate turns taken"]


class ShapeDebateState(TypedDict):
    """State for the curve-shape debate (steepener vs flattener).

    Runs second, conditioned on the direction debate's outcome.
    """
    steepener_history: Annotated[str, "Arguments for curve steepening"]
    flattener_history: Annotated[str, "Arguments for curve flattening"]
    history: Annotated[str, "Full debate conversation history"]
    current_response: Annotated[str, "Latest response in the debate"]
    direction_outcome: Annotated[str, "Outcome from the direction debate (context)"]
    judge_decision: Annotated[str, "Shape debate judge's decision"]
    count: Annotated[int, "Number of debate turns taken"]


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # Fixed-income analyst reports (replacing equity reports)
    macro_policy_report: Annotated[str, "Report from the Macro/Policy Analyst"]
    curve_technicals_report: Annotated[str, "Report from the Curve Technicals Analyst"]
    fed_speak_report: Annotated[str, "Report from the Fed Speak Analyst"]
    macro_calendar_report: Annotated[str, "Report from the Macro Calendar Analyst"]

    # Fixed-income debate states
    direction_debate_state: Annotated[
        DirectionDebateState, "State of the yield-direction debate"
    ]
    shape_debate_state: Annotated[
        ShapeDebateState, "State of the curve-shape debate"
    ]

